version: "3"

services:
  mongodb:
    image: mongo
    environment:
      - MONGODB_DATABASE="orders"
    ports:
      - '27017:27017'
    expose:
      - '27017'
  redis:
    image: redis
    ports:
      - '6379:6379'
    expose:
      - '6379'

  orders:
    build: ./orders
    environment:
      - NODE_ENV=development
      - DB_HOST=mongodb
      - REDIS_HOST=redis
    ports:
      - '3000:3000'
    links:
      - mongodb
      - redis
      - payments
      - delivery
    depends_on:
      - mongodb
      - redis
      - payments
      - delivery

  delivery:
    build: ./delivery
    environment:
      - NODE_ENV=development
      - DB_HOST=mongodb
    links:
      - mongodb
    depends_on:
      - mongodb

  payments:
    build: ./payments
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
    links:
      - redis
    depends_on:
      - redis